import type { PluginBundleFile } from './plugin-bundle.js';
import { PLUGIN_WINDOWS_SUPPORT } from './plugin-platform-support.js';

interface MarketplaceDocsOptions {
  readonly version: string;
  readonly pluginName: string;
  readonly marketplaceName: string;
}

function installation({ pluginName, marketplaceName }: MarketplaceDocsOptions): string {
  return `# Install Noodle Seed

Install the plugin once in your coding agent. It will use the compatible, plugin-managed Noodle CLI and connect the authenticated Noodle Developer MCP when those capabilities are available.

## Supported platforms

Use the plugin on macOS, or on Windows from ${PLUGIN_WINDOWS_SUPPORT.supportedShell} with Linux Node.js and npm. Native ${PLUGIN_WINDOWS_SUPPORT.unsupportedShells} are not supported execution shells. From PowerShell, install the supported environment with:

\`\`\`powershell
${PLUGIN_WINDOWS_SUPPORT.installCommand}
\`\`\`

Then open the Ubuntu Bash shell and run the host and plugin installation there.

## Claude Code

Run these slash commands inside Claude Code:

\`\`\`text
/plugin marketplace add NoodleSeed-com/plugins
/plugin install ${pluginName}@${marketplaceName}
\`\`\`

## Codex

Run:

\`\`\`sh
codex plugin marketplace add NoodleSeed-com/plugins
codex plugin add ${pluginName}@${marketplaceName}
\`\`\`

You can also open \`/plugins\` in Codex and install Noodle Seed from the configured marketplace.

## Cursor

Install Noodle Seed from the Cursor Marketplace when it is listed. Before directory approval, a Teams or Enterprise administrator can import \`NoodleSeed-com/plugins\` into a team marketplace. Cursor does not currently expose a verified one-line terminal install for this repository, so this guide does not invent one.

## Your first prompt

Open the project you want to work in and ask:

> Build an MCP app for this project with Noodle Seed. Validate it locally and show me the deployment plan before deploying.

The coding agent writes the application. Noodle Seed guides and operates the build, validation, test, and deployment lifecycle.

## Update

- Claude Code: run \`/plugin marketplace update ${marketplaceName}\`, then update the installed plugin from \`/plugin\`.
- Codex: run \`codex plugin marketplace upgrade ${marketplaceName}\`, then reinstall or update from \`/plugins\` when prompted.
- Cursor: update from the marketplace that supplied the plugin.

## Uninstall

- Claude Code: run \`/plugin uninstall ${pluginName}@${marketplaceName}\`.
- Codex: run \`codex plugin remove ${pluginName}\`.
- Cursor: remove Noodle Seed from Cursor's plugin settings.
`;
}

function howItWorks(): string {
  return `# How the developer plugin works

The plugin is a distribution bundle, not a vibe-coding product. Your coding agent authors and tests the TypeScript source in your repository; Noodle Seed supplies the platform knowledge and operates the supported lifecycle.

## Capability layers

1. **Bootstrap skill** — recognizes MCP/plugin work, calls supported plugin functions, and hands off to the project-local skill generated by \`noodle init\`.
2. **typed local operations** — the \`noodle-readiness\` MCP maps strict tool inputs to the release-pinned public CLI capabilities without requiring or exposing a global CLI command.
3. **Build Readiness MCP** — reports structured local lifecycle state and performs bounded setup, link, config, gate, deploy, and feedback operations for build-time widgets and agents.
4. **Developer MCP** — provides authenticated Noodle Cloud inspection and diagnosis across the signed-in user's live organization access; every scoped tool names its organization explicitly.
5. **MCP App UI** — renders decision-first Build Readiness and operational widgets in hosts that support MCP Apps. Coding agents running headless receive the same underlying structured results without needing a widget renderer.

## Normal lifecycle

\`prompt → author TypeScript → validate → test → preview/check → deployment decision → deploy → inspect/diagnose\`

The plugin intentionally contains no long-form references or examples. It defers to the richer project-local skill after \`noodle init\`, so every project carries the commands, examples, and defaults generated for its compatible Agent Kit.

With existing sign-in, \`preflight_build\` can inspect an explicit organization/application/environment before publication, without requiring a link. It returns the same prerequisite checklist as \`noodle deploy preflight --json\`; it does not set configuration, upload assets or mark the build as deployed. A passing report is not proof of a real backend operation or host journey.
`;
}

function securityAndPermissions(): string {
  return `# Security and permissions

Noodle Seed uses the same OAuth identity as the Console and CLI. One compact consent authorizes the Developer MCP resource; the connection then follows the user's current organization memberships and roles. Remote tools require an explicit organization on every scoped call, while the local CLI may keep a default organization for convenience. Every deploy remains attributable to that identity.

The plugin's private execution boundary uses an isolated host profile. The Developer MCP receives authenticated, tenant-scoped requests; it does not ask the coding agent to forward bearer tokens to application backends.

## Declared execution and network access

- The host starts the release-pinned local MCP privately. Agent guidance and tool results expose only supported functions and stable public \`noodle ...\` recovery commands, never a private installation path.
- On first use, npm may download the exact release-pinned CLI package from \`https://registry.npmjs.org\`. The plugin never resolves \`latest\` and does not require a global CLI install.
- The remote Developer MCP endpoint is \`https://cloud.noodleseed.dev/developer/mcp\`. Host OAuth supplies its own audience-bound credential; the plugin bundle contains no token or client secret.
- Local Build Readiness uses a stdio child process. It accepts fixed schemas for setup, build gates, exact-target linking, variables, secret-from-environment transfer, deploy, feedback, and cancellation rather than an arbitrary command, shell string, or path.

## Local files and data movement

- Each host keeps plugin CLI auth and target state under \`~/.noodle/plugin-profiles/<host>\`, separate from ordinary CLI state. The project skill and managed context are written only by an explicit \`init\` or \`agents setup --write\` flow.
- Source code is not uploaded to the Developer MCP. The coding agent edits source locally; the CLI compiles and deploys the artifact only after the normal deployment decision.
- A requested deployment preflight sends the compiled definition and asset metadata to the configured deployment service for validation. It sends no asset bytes and performs no backend operation. Routine login refresh may renew saved credentials.
- Secrets and OAuth credentials are excluded from manifests, plugin files, widget payloads, diagnostics, and feedback drafts. Application secrets are resolved by the hosted credential boundary.
- Noodle Seed does not send a feedback draft unless the user gives explicit approval for the exact previewed proposal and destination. Declining or ignoring the request performs no network call and causes no retry.

## Safe operating rules

- Sign in through the official OAuth flow; never paste access tokens, refresh tokens, secrets, or \`.env\` contents into chat.
- Review the explicit organization, application, environment, and deployment summary before a consequential action.
- Store application credentials with the typed secret-from-environment function or \`noodle secrets set ... --from-env NAME\`, and reference them as \`secret("NAME")\` in TypeScript. Never place the value in chat, a command argument, or a shell pipeline.
- Treat source code as local: the coding agent edits the repository and the CLI compiles the deployable artifact.
- Deployment and secret writes require the host's normal approval controls when the host is not running autonomously.
`;
}

function troubleshooting(): string {
  return `# Troubleshooting

## The plugin is installed but does not trigger

Start a new agent session in the project and mention “Noodle Seed” or “build an MCP app.” Confirm the plugin is enabled in the host's plugin browser.

## The managed CLI cannot start

The launcher preserves the original npm diagnostic. When npm cannot download or resolve the pinned package, it then emits a JSON error with code \`plugin_cli_bootstrap_failed\` and recovery steps. Check access to \`https://registry.npmjs.org\`, retry, then use the host's plugin update or reinstall flow if the failure continues. Do not install an unrelated global CLI as a workaround.

A normal \`noodle\` validation, compile, test, or deployment error is not rewritten as a bootstrap failure: its original output and exit code pass through unchanged.

## Readiness reports \`unsupported_platform\` on Windows

Run the host from ${PLUGIN_WINDOWS_SUPPORT.supportedShell}, not native ${PLUGIN_WINDOWS_SUPPORT.unsupportedShells}. From PowerShell, run \`${PLUGIN_WINDOWS_SUPPORT.installCommand}\`, then install Linux Node.js 24 and the coding-agent host inside Ubuntu before reinstalling the plugin.

## Build Readiness is disconnected

Restart the host after installation so it reloads the bundled MCP configuration. If the host cannot render MCP Apps, continue headlessly: validation, tests, and deploy still return structured results to the agent.

## Compatibility error

Update the marketplace and reinstall the plugin. Compatibility is release-bound across the plugin, CLI, and Developer MCP capability version; mixing versions is intentionally rejected.

## Authentication or target error

Complete OAuth sign-in once. For remote inspection, call \`get_context\` and pass the intended organization explicitly; for local CLI work, inspect or switch the saved default with \`noodle orgs current\` / \`noodle orgs switch\`. Ask the agent to show the full target before deploying.

For commands, host-specific setup, and current known issues, see <https://docs.noodleseed.dev>.
`;
}

export function renderPluginMarketplaceDocs(
  options: MarketplaceDocsOptions,
): readonly PluginBundleFile[] {
  return [
    { path: 'docs/installation.md', content: installation(options) },
    { path: 'docs/how-it-works.md', content: howItWorks() },
    { path: 'docs/security-and-permissions.md', content: securityAndPermissions() },
    { path: 'docs/troubleshooting.md', content: troubleshooting() },
  ];
}
