// Curated customer authentication, authorization, and delegated downstream auth guidance.

export function renderCustomerAuthAuthoringSections(): readonly string[] {
  return [
    '## Customer OAuth for remote MCP clients',
    '',
    'For `customerAuth.oidc(...)` and `.federatedOidc(...)`, the application developer owns the standards-compliant authorization server. Noodle verifies its access tokens; it does not proxy discovery, create OAuth clients, or repair the upstream server. For issuer `https://id.example.com/oauth`, publish the path-inserted RFC 8414 document at `https://id.example.com/.well-known/oauth-authorization-server/oauth` as direct unauthenticated HTTP 200 JSON — never a login redirect.',
    '',
    'That metadata must expose HTTPS `authorization_endpoint`, `token_endpoint`, `jwks_uri`, and RFC 7591 `registration_endpoint`; advertise authorization-code and refresh-token grants, Dynamic Client Registration, PKCE with `code_challenge_methods_supported: ["S256"]`, and public clients with `token_endpoint_auth_methods_supported: ["none"]`. Validate the exact RFC 8707 `resource` on authorize, code exchange, and refresh, then map approved versions of one app/environment to the stable audience configured in `customerAuth`; use distinct audiences across apps and environments. Publish only public signing keys in JWKS. Run `noodle auth doctor src/server.ts`; its issuer-readiness probes perform bounded read-only GET checks and never register a client. A successful `noodle deploy --access customers` reports the same readiness without turning a diagnostic failure into a failed deployment.',
    '',
    "The MCP client, or Devtools during local testing, opens the configured `authorization_endpoint`; Noodle does not submit the login form or manage the authorization server's session or CSRF cookies. Keep the login and consent UI plus credential POST on the same origin as the authorization endpoint. If a separate-site UI is unavoidable, the authorization server must explicitly trust the UI origin, use exact credentialed CORS where browser JavaScript calls it, issue the session and CSRF cookies needed by cross-site POSTs as `SameSite=None; Secure`, and return a CSRF token that the UI submits with credentials. Cookies cannot be shared across unrelated registrable domains. Browser privacy controls may still block this cross-site flow, so a same-origin route or reverse proxy remains the reliable design.",
    '',
    'Verify customer OAuth in three explicit layers. First run `noodle auth doctor src/server.ts --json`; a pass proves metadata and JWKS readiness, but it does not prove that registration or token issuance succeeds. Next run `noodle test src/server.ts --json`; for a protected app it proves that anonymous MCP access fails closed with exact protected-resource metadata and returns `interactiveRequired: true`. Finally run `noodle devtools src/server.ts`, complete sign-in, and make one authenticated `tools/list` request or one representative safe read. Only that final layer proves issuer, signature, stable audience, and exact-resource binding together. Never report a passing doctor or anonymous boundary smoke as working end-to-end authentication.',
    '',
    '## Auth-derived customer API endpoints',
    '',
    'Use a customer endpoint when the verified IdP selects a different API base URL for each SaaS customer. The claim contains the complete base URL; tool input and `${user}` do not select it. Declare one named policy, use that reference as the connector `baseUrl`, and map its claim path in direct OIDC or on every federated issuer:',
    '',
    '```ts',
    "import { annotations, connector, customerAuth, customerEndpoint, secret, server, tool, variable, z } from '@noodleseed/one';",
    '',
    "const customerApi = customerEndpoint('customer_api', {",
    "  allowedHttpsHostSuffixes: ['api.noodleseed.dev'],",
    '});',
    '',
    "const api = connector('customer_api_connector').version('1.0.0').http({",
    '  baseUrl: customerApi,',
    '  auth: {',
    "    kind: 'delegatedTokenExchange',",
    "    tokenUrl: 'https://id.noodleseed.dev/oauth/token',",
    "    clientId: variable('CUSTOMER_API_CLIENT_ID'),",
    "    clientSecret: secret('CUSTOMER_API_CLIENT_SECRET'),",
    '  },',
    '  operations: {',
    '    list_records: {',
    "      type: 'read',",
    "      method: 'GET',",
    "      path: '/records',",
    '      input: z.object({}),',
    '      output: z.object({ records: z.array(z.unknown()).max(100) }),',
    '    },',
    '    archive_record: {',
    "      type: 'action',",
    "      method: 'POST',",
    "      path: '/records/${args.record_id}/archive',",
    '      input: z.object({ record_id: z.string() }),',
    '      output: z.object({ archived: z.boolean() }),',
    '    },',
    '  },',
    '});',
    '',
    'export default server(',
    "  'customer_records',",
    '  {',
    "    title: 'Customer records',",
    "    version: '1.0.0',",
    '    use: { api },',
    "    interactions: { confirmationFallback: 'host' },",
    '    auth: customerAuth.oidc({',
    "      issuer: 'https://id.noodleseed.dev',",
    "      audience: 'noodleseed-customer-records-prod',",
    '      routing: {',
    '        endpoints: {',
    "          customer_api: { claim: 'tenant.api_base_url' },",
    '        },',
    '      },',
    '    }),',
    '  },',
    '  [',
    "    tool('list_records', {",
    "      description: 'List records for the signed-in customer.',",
    '      input: z.object({}),',
    '      output: z.object({ records: z.array(z.unknown()).max(100) }),',
    '      fulfil: ({ connectors }) => {',
    '        const result = connectors.api.listRecords();',
    '        return { records: result.records };',
    '      },',
    '    }),',
    "    tool('archive_record', {",
    "      description: 'Archive one record for the signed-in customer.',",
    '      input: z.object({ record_id: z.string() }),',
    '      output: z.object({ archived: z.boolean() }),',
    '      annotations: annotations.openAction({ destructive: false, confirm: true }),',
    '      fulfil({ input, connectors }) {',
    '        const result = connectors.api.archiveRecord({ record_id: input.record_id });',
    '        return { archived: result.archived };',
    '      },',
    '    }),',
    '  ],',
    ');',
    '```',
    '',
    '`customerEndpoint` accepts exactly one non-empty policy arm: exact HTTPS origins, or HTTPS hostname suffixes. Exact policies may authorize an explicit non-default port; suffix policies allow port 443 and match only the exact host or dot-boundary subdomains. Do not add connector `allowedOrigins` to a customer-routed connector. Its fixed credential/token endpoints are validated independently and cannot come from caller claims.',
    '',
    'Customer-routed connector auth must be omitted or use `delegatedTokenExchange` at both connector and operation level. The compiler validates the concrete connector definition emitted from TypeScript, including connector defaults and operation overrides. Do not emit bearer, API-key, client-credentials, or managed-provider fallbacks for local mode; use operation fakes while leaving auth declarative. `customer_endpoint_unsupported_auth` reports the exact failing path and auth kind.',
    '',
    "On a bidirectional MCP transport whose client negotiated form elicitation, Noodle sends the standard confirmation form. The current stateless hosted MCP transport cannot initiate that exchange, so the example explicitly declares `server.interactions.confirmationFallback: 'host'`. That fallback trusts the MCP host to have collected native write approval before the tool call reaches Noodle; it is never inferred from client identity and does not replace authentication, authorization, policy, or accurate action/destructive annotations. Omit it when connected hosts are not trusted to provide that approval; confirmation then fails closed with `interaction_unavailable` when the standard exchange is unavailable.",
    '',
    'Every federated issuer must repeat every endpoint key used by the app, although each issuer may choose a different claim path. Endpoint names use lowercase letters, numbers, and underscores. Resolved claims must be exact absolute HTTPS URLs of at most 2,048 UTF-8 bytes with no userinfo, query, fragment, IP literal, special-use host, or unsafe whitespace/control characters. The runtime preserves a canonical optional base path.',
    '',
    'Resolved customer URLs are private routing authority: they never enter the manifest/artifact, `${user}`, logs, model output, widgets, public confirmation review, cache keys, or delegated-token-exchange assertions. Routed reads may be used by tools, including declared nested calls. A routed action—including one reached through a connector wrapper—requires exact `annotations.confirm: true`; omitted or `false` fails with `customer_endpoint_action_unsupported`. Routed resources, prompts, and ambient context fail with `customer_endpoint_surface_unsupported`.',
    '',
    'At runtime, an initially missing, malformed, or disallowed claim returns the same safe `connector_route_unavailable` tool error before credential lookup or connector egress. Preparation stores only sorted route `{ key, fingerprint }` bindings in the private server-held continuation. Acceptance re-resolves the current request routes; a missing or changed binding returns `invalid_continuation` before policy, credentials, or egress, then the matching frozen snapshot is reused for the action and nested/later calls. `tools/list` follows the scope/role discovery rule and its explicit public-descriptor opt-in, so route availability neither reveals tenant topology nor changes execution authorization.',
    '',
    '## Per-tool authorization',
    '',
    'Keep endpoint authentication in `customerAuth.*(...)`, then narrow individual tools with the optional typed `authorization` rule. Every `requiredScopes` value is required; any one `allowedRoles` value is sufficient; when both lists are present, both conditions apply. Omit `authorization` for an unrestricted tool. Do not invent a policy expression language or infer authorization from tool arguments, page context, connector output, email domains, or other unverified data.',
    '',
    '```ts',
    'auth: customerAuth.oidc({',
    "  issuer: 'https://id.example.com',",
    "  audience: 'https://api.example.com/mcp',",
    "  claims: { roles: 'permissions.roles', scopes: 'permissions.scopes' },",
    '}),',
    '',
    "tool('list_org_apps', {",
    '  authorization: {',
    "    requiredScopes: ['org_apps:read'],",
    "    allowedRoles: ['org_admin', 'org_member'],",
    '  },',
    '  // input, output, and fulfilment...',
    '})',
    '```',
    '',
    "Use `authorization.discovery: 'public'` on a nonempty scope/role rule to expose its MCP descriptor before sign-in. Omission and explicit 'authorized' preserve filtered discovery and compile identically. Visibility grants no execution or product-skill eligibility; scopes remain ALL and roles ANY. Noodle derives securitySchemes; never author them.",
    'For mixed customer preview, keep server customerAuth and adopt on the same org/app/env, endpoint, issuer and audience; keep the separate public Help endpoint during the pilot, and never create overlapping active issuer/audience ownership. Before any mixed deploy or access change, leave only Help unrestricted, add authorization to every customer tool, and validate plus preview with `noodle dev --access mixed`. For an existing customer-only app, first run `noodle deployments list --org <org> --app <app> --env <env> --json` and inspect an inactive `customers` record for the exact server version. If none exists, record the active ID, redeploy the unchanged secured source to the same version with `--access customers`, then list and inspect again to prove that ID is now inactive; recording it alone preserves nothing. Next deploy the policy-prepared source with `--access customers`, verify the original rollback record remains inactive, and only then run `noodle access set mixed ... --version <version>`. On pilot failure use `noodle rollback <deployment-id> --org <org> --app <app> --env <env> --reason <text>`. This app-history rollback differs from the compatible hosted service-release floor. Invalid supplied credentials fail, with no platform-human fallback. Broker exchange remains required. Local Devtools retries after successful sign-in and leaves Help available after cancellation without executing the protected tool. After deployment, test anonymous discovery, sign-in, cancellation, authenticated retry and expiry in the actual host before customer cutover; local/SDK checks do not prove ChatGPT or another host.',
    '',
    'Role values are trusted only from the explicitly configured claim path (or the platform-private bridge role claim). Direct OIDC scopes default to standard `scope`, `scp`, or `scopes` claims unless `claims.scopes` is configured. Embedded-assistant backends pass verified `user.roles` and `user.scopes` separately during `createAssistantSession(...)`; page context never grants either. Claim values must be a string or string array; malformed or oversized values fail closed. Tools retain authored order in `tools/list`; protected descriptors are omitted unless explicitly public, and an unauthorized direct call is still denied before argument validation or connector execution. Scope denials use MCP OAuth step-up metadata without disclosing role names.',
    '',
    '## Delegated downstream auth (call your API as the signed-in user)',
    '',
    'Use delegated connector auth when the downstream API must enforce its own per-user authorization — a shared service credential plus a forwarded user id would bypass it. Three shapes exist; pick by who owns the downstream:',
    '',
    '`delegatedTokenExchange` consumes a verified customer caller; an MCP access mode does not create one. The server must declare `customerAuth.*(...)` or `embeddedAssistant(...)` so Noodle can establish the caller subject, issuer, and audience. Otherwise `noodle validate`, `noodle auth doctor`, and deploy fail early with `delegated_token_exchange_identity_required`, before secrets are resolved or any connector egress. A successful local Devtools exchange is not evidence that the hosted server has an identity source. Devtools supplies a separate, loopback-only local identity context that is never accepted by hosted deployment.',
    '',
    '- **`delegatedTokenExchange`** — your own API. The platform signs a short-lived, verifiable assertion of the signed-in user and exchanges it at a token endpoint you implement (RFC 8693). It works with verified customer OIDC identities and the built-in Firebase/Microsoft adapters; no per-user OAuth enrollment. Embedded-assistant sessions can bind customer-routed connectors when the authenticated embedding backend resolves each route from server-owned tenancy data and passes it during session exchange. Browser input, page context, session claims, and tool arguments cannot supply or override that private route authority.',
    '- **`delegatedOAuth` with `provider: "firebase" | "microsoft"`** — Noodle-managed bridge providers using stored per-user refresh tokens. Requires the matching `customerAuth` bridge; any other provider string is the compile error `unsupported_delegated_provider`.',
    '- **`delegatedSessionCookie`** — Firebase-managed session-cookie apps only; not a generic mechanism.',
    '',
    '### The connector (your `server.ts`)',
    '',
    '```ts',
    'auth: {',
    "  kind: 'delegatedTokenExchange',",
    "  tokenUrl: 'https://app.example.com/api/assistant/oauth/token', // fixed HTTPS; static connectors also allowlist its origin",
    "  clientId: variable('EXAMPLE_DELEG_CLIENT_ID'),",
    "  clientSecret: secret('EXAMPLE_DELEG_CLIENT_SECRET'),",
    "  scopes: ['time_off'],           // optional",
    "  audience: 'example-api',        // optional; assertion + request audience, defaults to tokenUrl",
    "  authMethod: 'client_secret_basic', // default; client_secret_post supported",
    '}',
    '```',
    '',
    'Inside tools, `${user.subject}` / `${user.email}` / `${user.name}` / `${user.locale}` / `${user.timeZone}` / `${user.claims.*}` stay available as verified context; the delegated credential is what makes the *downstream call itself* run as that user.',
    '',
    '### The exchange request your endpoint receives',
    '',
    'The broker POSTs `application/x-www-form-urlencoded` to `tokenUrl` with `Authorization: Basic base64(clientId:clientSecret)` (or `client_id`/`client_secret` form fields for `client_secret_post`):',
    '',
    '```',
    'grant_type=urn:ietf:params:oauth:grant-type:token-exchange',
    'subject_token=<RS256 JWT signed by the platform>',
    'subject_token_type=urn:ietf:params:oauth:token-type:jwt',
    'scope=time_off            (space-joined, when configured)',
    'audience=example-api      (when configured)',
    '```',
    '',
    'The `subject_token` claims: `iss` (platform issuer; JWKS at `{iss}/.well-known/jwks.json`), `sub` (verified user id), `aud` (your configured audience or the tokenUrl), `email`, `name`, `claims` (declared session claims), `tenant` (`org/app/env`), `deployment`, `customer_identity: { version: 1, issuer }`, `iat`, `exp` (about 120 s), `jti`. Key downstream users by `(customer_identity.issuer, sub)`, never by `sub` alone. Firebase uses `https://securetoken.google.com/<project-id>`; Microsoft uses `https://login.microsoftonline.com/<tenant-id>/v2.0`. A routed exchange adds `route: { key, fingerprint }`, never the customer URL; credential cache and single-flight keys include that route binding. Respond with `{ "access_token": "...", "token_type": "Bearer", "expires_in": 900 }`; the broker caches per user + connector + scopes + route until `expires_in` minus 300 s and presents the token downstream as `Authorization: Bearer`.',
    '',
    '### The downstream token endpoint (your backend)',
    '',
    '```ts',
    '// POST /api/assistant/oauth/token — Node example with jose.',
    "import { createRemoteJWKSet, jwtVerify } from 'jose';",
    '',
    'const PLATFORM_ISSUER = process.env.NOODLE_PLATFORM_ISSUER!; // e.g. https://cloud.noodleseed.dev',
    'const jwks = createRemoteJWKSet(new URL(`${PLATFORM_ISSUER}/.well-known/jwks.json`));',
    '',
    'export async function tokenEndpoint(req: Request): Promise<Response> {',
    '  // 1. Authenticate the broker client credential (client_secret_basic).',
    "  const basic = req.headers.get('authorization') ?? '';",
    "  const [clientId, clientSecret] = atob(basic.replace(/^Basic /, '')).split(':');",
    '  if (!isValidClient(clientId, clientSecret)) return new Response(null, { status: 401 });',
    '  // 2. Verify the platform-signed user assertion (never trust a plaintext user id).',
    '  const form = new URLSearchParams(await req.text());',
    "  const { payload } = await jwtVerify(form.get('subject_token') ?? '', jwks, {",
    '    issuer: PLATFORM_ISSUER,',
    "    audience: 'https://app.example.com/api/assistant/oauth/token', // your tokenUrl or configured audience",
    '  });',
    "  if (payload.deployment !== undefined && payload.tenant !== 'your-org/your-app/prod') {",
    '    return new Response(null, { status: 403 }); // optionally pin the calling deployment',
    '  }',
    '  // 3. Mint your own short-lived user-scoped token; your API enforces per-user rules from it.',
    "  const accessToken = await issueAccessToken(String(payload.sub), clientId, form.get('scope') ?? '');",
    '  return Response.json({ access_token: accessToken, token_type: "Bearer", expires_in: 900 });',
    '}',
    '```',
    '',
    '### Test delegated exchange locally',
    '',
    'Local customer OIDC sign-in and delegated-exchange assertion trust are two distinct boundaries. OIDC proves the caller to the local MCP server; Devtools uses a separate local issuer only for the RFC 8693 assertion sent to your downstream token endpoint. This requires no `server.ts` change or additional flag, environment variable, or config surface.',
    '',
    '1. Configure the OIDC authorization server for the exact loopback callback and RFC 8707 resource. Do not add the Devtools assertion key to OIDC issuer metadata or change its signing keys.',
    '2. Start Devtools, complete customer sign-in, and copy the displayed `{ issuer, jwks }` from **Local delegated exchange**.',
    '3. Pin both values only in the customer-owned development RFC 8693 token endpoint.',
    '4. Restrict that trust to development client credentials, audience, API, and data.',
    '5. Run the delegated tool until its binding reads **Exchange verified**.',
    '6. Use hosted preview or `noodle auth doctor --live` to prove the production platform issuer.',
    '',
    '**Never trust the Devtools issuer in production: anyone holding the local private key could impersonate a customer.**',
    '',
    'Diagnose statically with `noodle auth doctor`; set a short-lived real customer token only in `NOODLE_CUSTOMER_TOKEN` and add `--live --org <org> --app <app> --env <env>` to perform one exchange per delegated binding without invoking a business tool. Add `--version <version>` to test that exact pinned MCP resource. Common failures include structured `credential_unavailable` reasons such as `caller_identity_not_customer`. For a Firebase/Microsoft bridge, `caller_issuer_missing` means the session predates issuer binding: reconnect once through customer authentication, then retry. No IdP custom claim or `server.ts` change is required. Direct/federated OIDC verification assigns the customer identity at the trusted verifier boundary; never ask an IdP to mint a Noodle-specific classification claim.',
    '',
  ];
}
