// Curated authoring-side skill references: authoring-workflow, widgets-and-apps, examples.
// The widgets-and-apps hook table is rendered from the generated REACT_HOOKS surface plus the
// curated HOOK_NOTES map, so the documented hook list can never drift from the shipped SDK.
import { HOOK_NOTES } from './curated/hook-notes.js';
import { BUNDLED_EXAMPLE_FILES, BUNDLED_EXAMPLE_NAMES } from './generated/example-files.js';
import { REACT_HOOKS } from './generated/surface.js';
import { mdTable } from './md.js';
import { renderCustomerAuthAuthoringSections } from './skill-authoring-auth-ref.js';

// ----------------------------------------------------------------------------
// references/authoring-workflow.md (CURATED)
//
// The `export default server(` worked example below is compile-verified on every `pnpm test` via
// scripts/verify-skill-snippets.mjs (the real `noodle validate`, not raw `tsc`). The other connector
// fragments are illustrative operation-mapping shapes (skipped by the gate as non-full-server).
// ----------------------------------------------------------------------------

export function renderAuthoringWorkflowReference(): string {
  return [
    '# Authoring workflow',
    '',
    '## Contents',
    '',
    '- Input paths',
    '- Fit check',
    '- Product-guide decision',
    '- Repair loop',
    '- Connectors',
    '- HTTP connector example (full server)',
    '- Customer OAuth for remote MCP clients',
    '- Auth-derived customer API endpoints',
    '- Per-tool authorization',
    '- Delegated downstream auth (call your API as the signed-in user)',
    '- Invocation context',
    '- Compute connector example',
    '- Tests',
    '- Secrets and variables',
    '- Embedded assistant',
    '- Managed collections',
    '- Boundaries',
    '',
    '## Input paths',
    '',
    '1. **Website scrape** — if the user gives a URL, scrape it for surface hints (products, services, hours, contact, pricing). Stop there: the URL does not reveal CRM, booking systems, custom APIs, auth model, eligibility rules, quoting logic, or approval flows. Those live in the business systems and the owner’s head — ask.',
    '2. **OpenAPI import** — `noodle import openapi <file>` writes a pinned project at `src/server.ts`, shared operation/tool schemas, managed auth references, and an offline contract test. Supported JSON bodies become typed `input.body`, sent unchanged; unsupported request constraints/encodings stop import before writes. It does not install dependencies or call the backend. Follow its README, run `agent:check`, and add a reviewed sandbox-operation test; compile success is not live integration proof. Review auth warnings before deployment. Modified files are preserved unless `--force` is explicit.',
    '3. **Upstream MCP import** — `noodle import mcp <url> --name <slug> --output <dir>` discovers `tools/list` once, validates and freezes tool schemas into TypeScript, and writes a secret-free drift snapshot. Upstream annotations are untrusted, so generated tools remain destructive confirmed actions until an author verifies and narrows them. Use `--header-env <header>=<ENV_NAME>` for import-only auth and `--check` for classified, non-mutating drift detection. Runtime never performs discovery.',
    'Both imports use `src/server.ts` as the declared entrypoint, include an offline compile test and `.env.example`, and write files only. Install the pinned dependencies, run the generated checks, then `noodle agents setup --apply`. Never treat generated contract tests as customer authentication or business-workflow evidence.',
    '4. **User interview** — Noodle does not interview; you do. Cover custom APIs/integrations, eligibility rules, quoting/approval logic, and private schemas (SQL DDL or JSON samples for custom `connector` declarations). Ask for concrete examples and sample payloads; do not guess a schema from a URL or invent endpoints.',
    '',
    '## Fit check',
    '',
    'Before building, confirm the idea fits a conversational surface: 1–3 focused actions where saying it beats clicking, plus data or actions the model lacks on its own. Poor fits — long-form or static content, dashboards, deep multi-step navigation, or a full app port. When an idea does not fit, narrow the scope to the actions that do.',
    '',
    '## Product-guide decision',
    '',
    'Before authoring, record whether the product is guided or unguided and why. Do not wait for the user to name `agentGuide`; load `references/product-agent-guides.md` for the canonical decision criteria and TypeScript shape whenever product-level workflow guidance may add value.',
    '',
    '## Repair loop',
    '',
    'Author in `server.ts`, then `noodle validate` → fix cited errors (see `compile-errors.md`) → re-validate → `noodle test` → `noodle dev`. Keep the loop tight and error-driven.',
    '',
    '## Connectors',
    '',
    'Declare typed connectors:',
    '',
    '- **HTTP**: `connector("id").version("1.0.0").http({ baseUrl, allowedOrigins, auth, operations })`; map request/response with `${args...}` / `${response...}`. Use `${execution.id}` for provider idempotency, never model input. Optional `evidence: { outcome: "${response.execution_outcome}", reference: "${response.id}" }` classifies completed/rejected/accepted/unknown; reference is a bounded opaque ID, never a bearer URL or payload. No automatic action retry.',
    '- **MCP**: `connector("id").version("1.0.0").mcp({ endpoint, allowedOrigins, auth?, operations })` where each operation freezes the separate upstream `tool` wire name plus input/output schema. Import with `noodle import mcp`; do not hand-copy a live surface or call `tools/list` at runtime.',
    '- **Compute**: `connector("id").version("1.0.0").compute(name, { input, output, calls?, run })` — a self-contained, sandboxed function (no imports/closure capture) that may call allowlisted operations via `callOperation`.',
    '- **Explicit helpers**: `run: (input, host) => ...` can use `host.time.parse(iso)`, `host.time.format(epochMs)`, `host.time.parts(epochMs, timeZone)` and `host.digest(text, "hex")` (or `"base32hex"`). They convert bounded explicit data; there is no ambient clock. Pass trusted `context.temporal.instant` through fulfilment when current time is needed. `examples/weather` demonstrates a stable digest fallback for provider records without IDs.',
    '- **Expected HTTP errors**: declare `responses: { "409": { response: { status: "conflict" }, evidence: { outcome: "rejected" } } }` alongside the ordinary success `response`. Explicit 4xx overrides exclude 401/403/429; validate against the same output schema. Undeclared errors still fail. Overrides never inherit successful completion evidence or introduce action retries.',
    '- **Coordinated external actions**: a compute action may declare `coordination: { connectionId, namespace, key: "${args.resource}", reference: "${execution.id}" }` with a bounded execution deadline. It requires an installed application with a live bound connection and durable service coordination. Read `host.coordination.acquired` before writing; a blocked invocation may inspect `previous` through a declared read and call `host.resolveCoordination()` only after exact source proof, then require a fresh invocation/confirmation. The runtime permits at most one nested action when acquired and zero when blocked, even after recovery. Report explicit completed/rejected/unknown evidence with `host.reportOutcome(...)`; a successful return alone never unlocks uncertainty. Do not create an external-record collection for this.',
    '',
    'Tools record connector calls into a flow; recording is not execution. Do not branch on runtime outputs with native `if` — use declarative `when(...)` conditions.',
    '',
    'MCP connectors are curated backing operations, never transparent proxies. Publish ordinary Noodle tools',
    'with stable intent-shaped names, descriptions, annotations, authored schemas, confirmation, visibility,',
    'and optional React `view`. Normalize a text-only upstream result through compute before rendering when the',
    'view needs a richer stable output. Upstream resources, prompts, `_meta`, annotations, widgets, and CSP are',
    'not imported or forwarded. The runtime opens one guarded session for one operation, uses only a broker-minted',
    'credential, and closes it; it does not act as an agent for upstream sampling, roots, or elicitation.',
    '',
    'HTTP connector auth variants: `bearer` (`{ kind: "bearer", secret: secret("API_TOKEN") }`), `apiKey` (`{ kind: "apiKey", header: "X-API-Key", secret: secret("API_KEY") }`), `clientCredentials`, `delegatedOAuth`, `delegatedSessionCookie`, and `delegatedTokenExchange` (per-user calls to your own API — see "Delegated downstream auth" below). Use managed `secret(...)` / `variable(...)` refs for all values that differ by org/app/env.',
    'An application-owned adapter may require its own service credential in addition to the operator account credential. Declare `http.transportAuth: { kind: "apiKey", header: "X-Adapter-Key", secret: secret("ADAPTER_SERVICE_KEY") }` alongside bound account credential profiles; the credential broker supplies the two independently. Never put either credential in tool arguments or ordinary headers, and never reuse an inbound MCP bearer. This capability does not imply a provider requires two credentials.',
    '',
    'When one connector needs independently selectable accounts, declare catalog `credentialProfiles` plus each operation’s accepted `credentials.profiles`, then bind each `server.use` alias with `bind(connector, { profile, connection: connection("logical_id", managedSecret(secret("NAME"), { scopes, audience })) })`. The alias is the stable account boundary; never put provider account ids, labels, or credential values in it. `gmailConnector()` is the curated Gmail catalog helper; reuse it under independent aliases and accept canonical `accounts` arrays in tools (one account for writes, or an explicitly ordered supported combination for reads). See the bundled `gmail-multi-account` flagship. Bound managed secrets are supported by hosted execution. For deployed-server access to Google APIs, use `googleWorkloadIdentity({ provider: variable("GOOGLE_WIF_PROVIDER"), access: { kind: "direct" } })`, or add `serviceAccountImpersonation` with a managed service-account email. This is keyless Google Workload Identity Federation: exact Google scopes/audience come from the catalog operation, while `noodle auth google prepare|status|doctor|revoke` owns operator lifecycle. See the bundled `google-bigquery` flagship. `externalExchange()` is runnable only when the deployment operator injects an exact HTTPS provider endpoint/origin/audience and durable shared subject-pin store through service ports; Noodle sends a short-lived platform-signed deployment workload assertion and accepts only a bounded bearer response. Provider implementations must consume assertion replay ids through durable shared atomic storage across instances and restarts. There is intentionally no hosted enrollment or provider CRUD surface yet. The provider wire contract is public, but its conformance kit is workspace/source-only and is not an installable npm package. Bound `clientCredentials(...)` remains fail-closed until its provider slice lands.',
    '',
    '## HTTP connector example (full server)',
    '',
    'Declare the API as data, bind it with `use`, then record calls in tools. The operation mapping in detail: `request` builds the JSON request body, `query: [...]` names the input args sent as URL query parameters, and `response` maps the parsed HTTP body (bound to `${response}`) into your typed `output`. `auth` reads a managed `secret(...)` — never inline a key. This whole example is compile-verified on every `pnpm test`.',
    '',
    '```ts',
    "import { connector, secret, variable, server, tool, z } from '@noodleseed/one';",
    '',
    "const crm = connector('crm').version('1.0.0').http({",
    "  baseUrl: variable('CRM_BASE_URL'),",
    "  allowedOrigins: ['https://api.crm.example'],",
    "  auth: { kind: 'bearer', secret: secret('CRM_TOKEN') },",
    '  operations: {',
    '    find_customer: {',
    "      type: 'read',",
    "      method: 'GET',",
    "      path: '/customers',",
    "      query: ['email'],",
    '      input: z.object({ email: z.string() }),',
    '      output: z.object({ id: z.string(), name: z.string().optional() }),',
    "      response: { id: '${response.data[0].id}', name: '${response.data[0].name}' },",
    '    },',
    '    create_ticket: {',
    "      type: 'action',",
    "      method: 'POST',",
    "      path: '/tickets',",
    '      input: z.object({ customer_id: z.string(), body: z.string() }),',
    '      output: z.object({ ticket_id: z.string() }),',
    "      request: { customer_id: '${args.customer_id}', body: '${args.body}' },",
    "      response: { ticket_id: '${response.id}' },",
    '    },',
    '  },',
    '});',
    '',
    "export default server('support', { title: 'Support', version: '1.0.0', use: { crm } }, [",
    "  tool('find_customer', {",
    "    description: 'Find a customer by email address.',",
    '    input: z.object({ email: z.string() }),',
    '    output: z.object({ id: z.string(), name: z.string().optional() }),',
    '    fulfil: ({ input, connectors }) => {',
    '      const customer = connectors.crm.find_customer({ email: input.email });',
    '      return { id: customer.id, name: customer.name };',
    '    },',
    '  }),',
    "  tool('open_ticket', {",
    "    description: 'Open a support ticket for a customer.',",
    '    input: z.object({ customer_id: z.string(), body: z.string() }),',
    '    output: z.object({ ticket_id: z.string() }),',
    '    fulfil: ({ input, connectors }) => {',
    '      const ticket = connectors.crm.create_ticket({ customer_id: input.customer_id, body: input.body });',
    '      return { ticket_id: ticket.ticket_id };',
    '    },',
    '  }),',
    ']);',
    '```',
    '',
    'Naming: connector operation names and tool names are lowercase-with-underscores. Map with `${args.field}` for tool/operation inputs and `${response.path}` for the response — the parsed JSON body is bound directly to `${response}`, so there is **no `.body` envelope**; use bracket syntax for array indices (`${response.data[0].id}`) — a dotted numeric index like `.0.` is invalid. Declare URL query parameters with the operation-level `query: ["arg"]` array, **not** inside `request` (which builds only the JSON body). `allowedOrigins` is the SSRF allowlist: use literal exact origins, or the same `variable("STORE_ORIGIN")` as `baseUrl` when one reusable single-origin app is bound per business. A managed origin must resolve to one canonical bare HTTPS origin (exact loopback HTTP is the development exception); never use a wildcard, path, or tenant source edit.',
    '',
    'More: `auth.kind` is `bearer` | `apiKey` (needs `header`) | `clientCredentials` | `delegatedOAuth` | `delegatedSessionCookie` | `delegatedTokenExchange`. For client credentials use `{ kind: "clientCredentials", tokenUrl, clientId, clientSecret, scopes? }` (RFC-6749 grant); for a non-standard partner token endpoint add `profile: "custom"` with a `custom: { requestFormat, clientIdField, clientSecretField, tokenResponsePath, expirySource }` descriptor. Do not put credential headers in operation `headers`; use connector `auth`. Use `.compute(name, { input, output, run })` for a sandboxed transform; `provides:` (instead of `use:`) exposes a connector only to compute `callOperation`; and `noodle import openapi <file>` generates a connector from an OpenAPI spec.',
    '',
    ...renderCustomerAuthAuthoringSections(),
    '## Design tools for the model',
    '',
    'Shape tools around what a user says, not 1:1 around API endpoints. `references/tool-design.md` owns the doctrine: intent-shaped tools, titles and annotations, bounded outputs, a small tool surface, and deliberate context.',
    '',
    '## Invocation context',
    '',
    'Every executable invocation receives one immutable server-authoritative temporal snapshot. TypeScript authoring does not create a hidden context tool. Use `server(..., { context })` for locale/time-zone defaults and trusted ambient facts, and designate one normal zero-input tool with `contextProvider: true` when the model needs portable application context. The embedded host preloads it per turn; Claude, ChatGPT, and other MCP hosts call it normally.',
    '',
    '```ts',
    'context: {',
    "  defaults: { locale: 'en-GB', timeZone: 'Europe/London' },",
    '  ambient: {',
    '    output: z.object({ defaultTeamId: z.string(), holidays: z.array(z.string()) }),',
    '    fulfil: ({ user, context, connectors }) => {',
    '      const calendar = connectors.people.getCalendar({',
    '        subject: user.subject,',
    '        asOf: context.temporal.instant,',
    '      });',
    '      return { defaultTeamId: calendar.default_team_id, holidays: calendar.holidays };',
    '    },',
    '  },',
    '},',
    '```',
    '',
    'Ambient providers are recorded as fulfilment data at author time, may call read-only connector operations only, and have a declared output schema. Later fulfilments read `${context.temporal.localDate}`, `${context.temporal.timeZone}`, `${context.ambient.defaultTeamId}`, and `${context.ambientStatus}`. If ambient resolution fails, the status is `unavailable`; never invent the missing business facts. Ambient/model-visible context is capped at 16 KiB serialized JSON, depth 8, and 128 entries per container; credential-shaped keys are rejected.',
    '',
    'Direct MCP tool calls may also expose an optional, untrusted client hint as `${context.location.latitude}` and `${context.location.longitude}`, with optional `${context.location.city}`, `${context.location.region}`, `${context.location.country}`, and `${context.location.timeZone}`. Noodle exposes location only when the host supplies one complete, finite, in-range coordinate pair. Treat it as a proximity convenience only: never use it for authentication, authorization, policy, compliance, or delivery-address proof. An explicit tool input must override the hint. When location is absent and the operation needs it, ask the user or return a structured location-required result; never substitute a fixed default location.',
    '',
    '## Ask for structured missing input',
    '',
    'Use `ctx.elicit` inside a tool fulfilment when execution needs one bounded value from the user. The call records an `elicit` flow step and returns its symbolic scope; it does not prompt at author time:',
    '',
    '```ts',
    "tool('prepare_time_off', {",
    "  description: 'Resolve a time-off request before proposing the write.',",
    '  input: z.object({ start: z.string(), end: z.string() }),',
    '  output: z.object({ start: z.string(), end: z.string(), teamId: z.string() }),',
    '  fulfil: ({ input, elicit }) => {',
    '    const answer = elicit({',
    "      id: 'choose_team',",
    "      message: 'Which team should receive this request?',",
    "      input: z.object({ teamId: z.string().describe('Team') }),",
    '    });',
    '    return { start: input.start, end: input.end, teamId: answer.teamId };',
    '  },',
    '});',
    '```',
    '',
    'Use a stable lowercase/number/underscore id and a flat form of string/number/integer/boolean, string choices or multi-select, with optional `email`, `uri`, `date`, or `date-time` formats. Nested objects and credential-shaped fields fail with `invalid_elicitation_schema`. Every interactive flow must place all `ctx.elicit` calls before its first connector operation or compilation fails with `invalid_elicitation_flow`. Embedded/headless clients receive `input_requested`; bidirectional MCP transports map the primitive to standard form `elicitation/create`. On stateless hosts, the adapter returns a structured non-executing `interaction_unavailable` result; linked Apps render its business-user form and retry in request `_meta`, while models can use the advertised reserved retry field. Accept validates and replays only the operation-free input prefix; invalid content returns `arg_invalid`, and decline/cancel stop. Elicitation gathers missing input and does not replace confirmation. In a flow marked `confirm: true`, every eligible `input_requested` precedes `tool_proposed`; the final proposal reviews the original input, elicited values, and sole exact eligible connector action. Conditional branches may declare multiple candidate actions only when preparation resolves exactly one eligible action from input/context or completed pure steps; zero or multiple actions fail with `invalid_confirmation_flow` before I/O. Acceptance is bound to that exact action. Later read-only operations and pure compute may assemble output, but a second eligible action fails closed. Use `ref.at(index)` for array access in recorded expressions. MCP uses final standard form confirmation on capable bidirectional transports and fails closed otherwise. Setting `interactions: { confirmationFallback: "host" }` in the server options explicitly trusts native host approval only when confirmation transport is unavailable and after every elicited field is collected; it still uses preparation and prepared execution, is never inferred from client name, and does not replace authorization. Omitted or `false` annotations execute directly; hints alone never gate. `annotations.action({ confirm: true })` explicitly enables confirmation; `annotations.action({ confirm: false })` explicitly preserves direct execution.',
    '',
    '## Compute connector example',
    '',
    '```ts',
    "const scoring = connector('scoring').version('1.0.0').compute('normalize', {",
    '  input: z.object({ email: z.string(), priority: z.string().optional() }),',
    '  output: z.object({ score: z.number() }),',
    "  calls: { find_customer: 'crm.find_customer' },",
    '  limits: { timeoutMs: 1000, maxHostCalls: 2 },',
    '  run(input, { callOperation }) {',
    '    const customer = callOperation("find_customer", { email: input.email }) as { id?: string };',
    '    return { score: customer.id && input.priority === "high" ? 100 : 50 };',
    '  },',
    '});',
    '```',
    '',
    'Compute `run` functions are serialized and sandboxed: no imports, no closure capture, no `fetch`, no `process`. Any backing-system call must be declared in acyclic `calls` and invoked through `callOperation`. For conditional flow edges, use `when(...)` in recorded fulfilment instead of native branching on connector outputs.',
    '',
    '## Tests',
    '',
    'Start from the generated `test/server.test.ts`, not a blank test file. `npm test` runs `vitest run --dir test` over the project-owned `test/` directory; skill-local example tests are reference material. The generated suite compiles the actual source/view, lists tools, asserts a representative result and rejects invalid input. It copies source into temporary fixture storage and uses synthetic configuration, never customer secrets or saved hosted targets. The HTTP profile proves one local backend read and zero extra calls for invalid input.',
    '',
    '```sh',
    'npm test',
    'npm run agent:check',
    '```',
    '',
    'Adapt the representative arguments and assertions when business contracts change; keep invalid-input and authorization cases. A name/export assertion or `noodle test --json` without `--tool` proves no useful call. After fixture tests pass, bind the real local configuration, run an authorized representative read, and use `noodle dev` for interactive checks. Never use a production mutation or fixture success as customer-readiness evidence.',
    '',
    '## Secrets and variables',
    '',
    'Author managed config as `secret("NAME")` / `variable("NAME")` and operate it with `noodle secrets set` / `noodle variables set` (scoped org/app/env). Never inline secret values in `server.ts`, tests, or generated files.',
    '',
    'For business-editable configuration, declare `const guestExperience = variable("GUEST_EXPERIENCE", { schema: z.object({ notice: z.string().max(500) }), default: { notice: "Welcome" }, portal: { label: "Guest experience" }, requiredFor: ["show_menu"] })` and register it in `server(..., { variables: [guestExperience], ... }, tools)`. Use the whole ref or `guestExperience.field("notice")` in ordinary fulfilment/connector arguments. `.field()` selects a schema-declared object property, can chain for nested objects, and retains the parent variable and full configuration snapshot; it never reads operator data at author time. Keep confirmed action arguments shallow enough for complete review; do not label ordinary settings sensitive to bypass the review. The default is reusable safe intent; each business supplies its own values without editing source. Only explicit `portal` metadata exposes a setting. Name-only references and declared variables without `portal` remain technical configuration; secrets remain credential slots. See the bundled `acme-bistro` source.',
    '',
    'Business schemas must be bounded: booleans, finite bounded numbers, bounded text, string enums, bounded arrays, and closed objects. Put defaults in the declaration, not inside Zod schema defaults; custom transforms/refinements and arbitrary schema code cannot run in the shared runtime. `requiredFor` names existing tools whose invocation needs the value; unresolved settings must leave only dependent capabilities unavailable. Publisher compilation does not require a future buyer’s values. Application code enforces business rules server-side; exposing a control or placing the rule in a prompt is insufficient.',
    '',
    'For an installed application, use the same `noodle variables list|resolve|set|delete` family with `--installation <id> --org <org> --runtime cloud|other`; do not combine it with app/env/scope flags or secrets. Inspection shows schema metadata, provenance, readiness and revision without saved values. Set inputs are JSON (including quotes for strings), read the current projection and save atomically; `--expected-revision <digest>` pins an explicit prior inspection. Delete resets to the current declared default or unset state. Business-administrator permission is required for mutations, conflicts never retry writes, and mutation output excludes values.',
    '',
    '## Embedded assistant',
    '',
    'To place the same server tools inside a SaaS web app, declare `assistant: embeddedAssistant(...)` alongside the one server-level brand kit. Read `embedded-assistant.md` before integrating: it owns the HTTPS-origin rule, managed model configuration, required deploy-before-client sequence, customer-backend exchange, browser mount, and verification checklist.',
    '',
    '## Managed capability reuse',
    '',
    'Before authoring an HTTP connector for public-web search, page extraction, places/local search, routing, weather, translation, or media discovery, inspect the generated SDK surface reference. If the matching Noodle capability is actually exported, use its one documented declaration and generated tools directly—never wrap it, rename it, or build an assistant-only provider call. That single declaration is available to both the embedded assistant and external MCP agents under the same authorization and policy.',
    '',
    'Use `provider: noodleManaged()` in reusable capability intent and let the app/environment operator bind a supported BYO provider through managed configuration. Keep provider names, endpoints, and credentials out of `server.ts`. Live fares, inventory, bookings, pricing, orders, accounts, and payments remain connectors to authoritative systems. Source order is not truth: preserve citations, freshness, and rights evidence returned by the capability.',
    '',
    'A roadmap is not an SDK. If the capability is absent from the generated export list, do not invent an import or generic platform helper. With explicit developer agreement, a bounded application connector may prove the immediate use case; keep it application-specific and do not claim it as the canonical Noodle primitive.',
    '',
    '## Knowledge components',
    '',
    "Ground an assistant in controlled documents and the customer's live public site with one declaration — never a handwritten `search`/`fetch` tool pair, a provider name, a sync job, or an index manifest. Declare `knowledge(...)` with `file(...)` documents (UTF-8 `.md`/`.txt`, project-root relative, ≤100 files, ≤1 MiB each, ≤25 MiB per component) and `site(...)` live scopes (exact HTTPS origin plus positive path globs), pass the declaration in the server's `knowledge` array, and include it in a public website surface's `capabilities` to project the generated `search_<name>` capability:",
    '',
    '```ts',
    "const product = knowledge('product', {",
    "  title: 'Product knowledge',",
    "  description: 'Public product, pricing, and support information.',",
    '  documents: [',
    "    file('./knowledge/product.md', { title: 'Product guide' }),",
    "    file('./knowledge/faq.txt', { title: 'FAQ' }),",
    '  ],',
    '  sites: [',
    "    site({ origin: 'https://www.acme.example', include: ['/docs/**', '/pricing'], refresh: '6h' }),",
    '  ],',
    '});',
    '```',
    '',
    'The compiler validates and hashes every document at build time (bad extensions, root escapes, symlinks, oversize, and non-UTF-8 fail `noodle validate` with the exact path); deployment publishes versioned files transactionally with the app, crawls declared sites, and re-crawls them on the `refresh` cadence (`15m`–`7d`, default daily; `noodle knowledge refresh <name>` crawls on demand). Component names are lowercase snake-case; each component implies exactly one generated bounded search capability with cited results.',
    '',
    "The managed crawler and managed index are the defaults and need no configuration. A component may instead bring its own crawler (`crawler: firecrawl({ apiKey: secret('FIRECRAWL_API_KEY') })` or `tavily(...)`) and/or its own index (`index: algolia({ appId: variable('ALGOLIA_APP_ID'), apiKey: secret('ALGOLIA_API_KEY') })` or `meilisearch({ host: variable(...), apiKey: secret(...) })`). The code declares only config names; operators supply values with `noodle secrets set` / `noodle variables set`, and deploy preflight fails closed naming any unset reference.",
    '',
    '## Managed collections',
    '',
    'Use `managedCollection(name, { title, description, schemaVersion, record })` when an application needs reusable typed intent for business records that Noodle may later hold. Pass it through `server(..., { collections: [...] }, definitions)`. `record` is one bounded, closed Zod object; names use lowercase letters, numbers, and underscores. Keep payment-card, credentials, passport/government identity, health, and biometric fields out of this surface.',
    'Native record controls are independent: `management: { assignment: true }`, `{ notes: true }`, both, or neither. Status is an ordinary application field such as `progress: z.enum(["received", "reviewing", "handled"]).default("received")`; no framework transition graph exists. Declare `publicFields` explicitly (default empty), `editableFields` for authorized staff (default all schema properties), optional field labels/help, `summaryFields`, `filterFields` and `sortFields`. References must name actual fields and filters/sorts select scalars. Public callers cannot set staff-only fields; a required private field needs a valid creation default. Staff updates merge only admitted fields and revalidate the complete record. See the notes-only `acme-bistro` collection.',
    'Operator record queries use `noodle solutions records list --filters \'[{"field":"progress","value":"received"}]\' --sort-field progress`. Only declared scalar equality/sort fields apply. Payload queries scan at most 10,000 candidates; narrow `--created-at-from`/`--created-at-to` if the API returns `query_limit_exceeded`. Ordinary listing/export has no such scan cap. Cursor reuse requires unchanged query/schema and anchor revision. An administrator can explicitly migrate an eligible historical request with `records migrate-schema ... --expected-revision N`; never implement read-time rewrites.',
    '',
    'Omitting `source` makes Noodle authoritative for the collection. To project a read-only collection from an outside system, bind an HTTP connector in `server(..., { use: [...] })` and add `source: { connector: connector.ref(), scan: "scan_operation" }`. The compiler requires the exact normalized scan contract and the same record schema. Noodle ingests a one-way replica; create, update, and delete in the outside system remain ordinary application tools with their own confirmation and policy.',
    '',
    'For an explicitly authored native operation, bind `use: { records: noodlePlatform.records.v1 }` and call `connectors.records.submitRecord({ collection: "guest_requests", payload: input })` from an ordinary confirmed tool. Submission accepts only public fields and returns a receipt. `createRecord`, `getRecord`, `listRecords`, `updateRecord`, and `deleteRecord` require a verified platform caller with a live business grant; updates/deletes require the current revision. `updateRecord({ collection, id, expectedRevision, patch, unset: ["optional_field"] })` removes named optional editable fields; omitted keys stay unchanged, `null` is data, and overlap with `patch`, required fields or undeclared fields is rejected. Runtime identity supplies write idempotency and admission; never accept those controls as model arguments. An uninstalled collection is unavailable, including during local tool execution.',
    'A collection declaration does not create a submit tool, grant access, select retention or residency, provision storage, or expose records to MCP or an embedded assistant. Operators activate the definition and configure lifecycle, access, and any external binding. A connector does not become a collection unless the app explicitly supplies the source contract, and an external collection never becomes a writable mirror.',
    '',
    '## Boundaries',
    '',
    'Import public app authoring only from `@noodleseed/one` (and its documented `/react` or `/platform` subpaths). Packages and subpaths under `@noodle-borg/*` are runtime implementation details, including `/portable` boundaries, and must never appear in customer `server.ts` code. Do not hand-author manifest JSON/YAML, runtime artifacts, connector IR, or hosted asset metadata. Do not read or copy secrets, bearer tokens, refresh tokens, static access keys, `.env`, `.env.noodle`, or `~/.noodle/config.json`. Hosted access is identity-based — do not add static data-plane credential paths.',
  ].join('\n');
}

// ----------------------------------------------------------------------------
// references/widgets-and-apps.md (CURATED prose + compile-verified recipe + GENERATED hook table)
//
// The two `export default server(` recipes below are compile-verified on every `pnpm test` via
// scripts/verify-skill-snippets.mjs. The view component fragment pairs (in document order) with the
// `entry:` of the first full-server recipe — keep exactly one non-full-server ```tsx fragment ahead
// of the widget recipe so the gate's fragment→entry pairing stays correct.
// ----------------------------------------------------------------------------

export function renderWidgetsAndAppsReference(): string {
  const hookRows = REACT_HOOKS.map((hook) => [`\`${hook}\``, HOOK_NOTES[hook] ?? '—']);
  return [
    '# MCP Apps and widgets',
    '',
    '## Contents',
    '',
    '- Tools and views',
    '- React hook surface',
    '- Worked widget recipe',
    '- ChatGPT App = this widget + a domain',
    '- Knowledge/source apps (search + fetch)',
    '- Permissions and host bridge',
    '- Readiness and boundaries',
    '',
    '## Tools and views',
    '',
    'Use `tool(name, { description, input, output, fulfil, view })` for a model-visible tool that renders a widget, and the same `tool(name, { ..., visibility: ["app"] })` for an app-only helper hidden from the model. When a view is valid only for narrow explicit intent, add `modelVisibility: { latestMessageIncludesAny: ["open the form", ...] }`; Noodle normalizes and matches those literal phrases against the latest user message before model discovery and fails closed on malformed data. Add `oncePerSession: true` when a successful model-selected view must not repeat in that conversation, and `requiredWhenVisible: true` only when a matching turn must render that sole required tool before normal model discovery resumes. These options control presentation and relevance, never idempotency or authorization. A `view` is `{ component: "name", entry: "./views/name.tsx" }` — a React component the compiler bundles at validate/deploy time.',
    '',
    '## Noodle Design default',
    '',
    'Generated widgets, official examples, and agent-authored MCP Apps must start with `@noodleseed/one/react` primitives and semantic tokens. Custom React/CSS or third-party components remain valid when the kit lacks the required behavior or the developer explicitly requests them.',
    '',
    '`noodle init my-app` defaults to an embedded-first SaaS profile: managed website assistant, operator-bound `ASSISTANT_ORIGIN`, context-provider read, MCP App UI, resource, prompt, state contract and branding. It installs pinned local tooling and verifies synthetic behavior; previews do not save customer changes. No placeholder IdP or handoff destination is enabled. Bind the application origin, then reuse the maintained host and customer-auth recipes and prove the real boundary. Use `--template widget`, `hello`, or `http-api` only when intentional.',
    '',
    'The default composition rule is: build the smallest useful conversational surface. Inline has one purpose, one primary action, and at most two visible actions. Use progressive disclosure or a later conversational turn for secondary detail; request fullscreen only when the user asks or the task genuinely needs it. Never use nested scrolling. At 280px and wider, the widget must remain one-column, readable, touch-safe, and free of horizontal overflow. Remove secondary chrome before shrinking essential content.',
    '',
    'Treat 1 MiB of uncompressed UTF-8 HTML as the recommended initial React-widget budget, not a compatibility wall. Noodle Seed accepts up to 10 MiB per compiled widget and 20 MiB across a deployment; `noodle check` reports raw and gzip-estimated sizes. Keep large media and dynamic datasets in hosted assets/resources or bounded app-only tool responses instead of inflating the initial widget resource.',
    '',
    'Every production widget handles loading, empty, partial, stale, error, retry, and success states. Prefill fields from known tool results and choose safe, reversible defaults; preserve the user’s work across rerenders, and never preselect a consequential action. Use public React primitives and branding tokens. Never author against `ns-*`, `nsr-*`, or example-local `--nw-*` classes/tokens; those are implementation details, not alternate design systems.',
    '',
    'Keep the complete `useToolInfo()` result. An empty result envelope is pending, `isError` is an explicit tool error, and any non-pending success must validate every required field and identifier before it becomes UI data. Render a malformed-result error when validation fails, and render dependent actions only after validation succeeds. Safe local input defaults may follow valid hydration; they must never fabricate a loaded business record.',
    '',
    '## React hook surface',
    '',
    'Author views as React components. `generateHelpers<ServerDefinition>()` (from `@noodleseed/one/react`) returns the typed host hooks:',
    '',
    mdTable(['Hook', 'Use for'], hookRows),
    '',
    'Bind interactive elements to tools (`useCallTool("place_order")`), keep bridge-backed controls disabled until `useWidgetReady()` is true, drive named views with `useAppFlow(...)`, open server-created handoffs with `useHandoff()`, and publish one compact, safe, cohesive snapshot with `useUpdateModelContext()` when `useLayout().supports?.modelContext` is true. Generated form workflows use the portable `<Form onSubmit={() => void submit()}>` component with a submit button; never use an intrinsic React `<form>` or add browser-navigation `action`, `method`, or `target` attributes. A sandbox can block native activation before React receives `onSubmit`, so `preventDefault()` inside an intrinsic handler is not a portability fix. Standalone actions use an explicit `type="button"` and call the tool from their click handler. In every case the widget calls the standard MCP Apps tool bridge itself — never rely on a host to translate native form submission into a tool call, and never branch on a host name. Every model-context or lifecycle publication replaces the prior snapshot rather than merging fields, so include everything the model should still know. Calling `useWidgetLifecycle("name")` automatically publishes `mounted`, listens for host `cancelled` and `dismissed`, and returns a publisher for author-owned `submitted` or app-specific milestones; `mounted` is not proof that the host presented pixels. Both hooks use the standard MCP Apps model-context channel, not a host-specific API. These updates affect future model context but do not start a model turn. When an explicit user submit/cancel should receive an immediate reply, also call `useSendFollowUpMessage()` from that user action. `data-llm` may remain a DOM inspection hint, but it is not the bidirectional model-state contract. Use `createViewStore("key", initial)` for multi-component widget state such as carts, filters, or drafts. Use the domain-neutral React components from `@noodleseed/one/react` (`AppShell`, `ShellNav`, `ViewStack`, `AsyncBoundary`, `ActionBar`, `Form`, `Field`, `QuantityStepper`, `ChoiceGroup`, `HandoffButton`, and related state components) for rich apps before inventing local shell/control scaffolding. Adapt to the host with `useLayout()` — style for both `theme` values, and keep the inline `displayMode` compact (content fits the space; no internal scrolling). Trigger `useOpenExternal()`, `useHandoff()`, and `useSendFollowUpMessage()` only from explicit user actions. A raw `html` escape hatch exists for self-contained widgets (declarative `data-bind`/`data-action`; no inline `<script>`); use a `data-action` button with `type="button"` instead of native form submission.',
    '',
    '## Worked widget recipe',
    '',
    'Minimal, complete, and compile-verified — `noodle validate` bundles the view and `noodle check --target chatgpt` audits it. Author two files: the view (`src/views/order-status.tsx`) and the tool declaration (`src/server.ts`).',
    '',
    '### 1. The view component',
    '',
    'Author React. `generateHelpers<ServerDefinition>()` (from `@noodleseed/one/react`) returns the typed host hooks: read the tool result with `useToolInfo`, call a widget-only helper with `useCallTool`, keep local UI state that survives re-render with `useViewState`, open an allowlisted link with `useOpenExternal`, and publish cohesive model-context snapshots plus author-owned lifecycle milestones.',
    '',
    '```tsx',
    "import { useEffect } from 'react';",
    "import type { ServerDefinition } from '@noodleseed/one';",
    "import { Action, ActionBar, AsyncBoundary, Feedback, Field, Flow, Frame, Region, Select, generateHelpers } from '@noodleseed/one/react';",
    '',
    '// One call wires the typed host bridge; destructure only the hooks this view uses.',
    'const { useToolInfo, useCallTool, useViewState, useLayout, useOpenExternal, useSendFollowUpMessage, useUpdateModelContext, useWidgetLifecycle, useWidgetReady } =',
    '  generateHelpers<ServerDefinition>();',
    '',
    'type OrderResult = {',
    '  readonly customer: string;',
    '  readonly item: string;',
    '  readonly total: number;',
    '  readonly checkoutUrl: string;',
    '};',
    '',
    'function isOrderResult(value: unknown): value is OrderResult {',
    "  if (value === null || typeof value !== 'object') return false;",
    '  const result = value as Partial<OrderResult>;',
    '  return (',
    "    typeof result.customer === 'string' && result.customer.length > 0 &&",
    "    typeof result.item === 'string' && result.item.length > 0 &&",
    "    typeof result.total === 'number' && Number.isFinite(result.total) &&",
    "    typeof result.checkoutUrl === 'string' && result.checkoutUrl.startsWith('https://')",
    '  );',
    '}',
    '',
    'export default function OrderStatus() {',
    '  const ready = useWidgetReady();',
    "  const toolInfo = useToolInfo('show_order');",
    '  const isPending = !ready || Object.keys(toolInfo).length === 0;',
    '  const shown = isOrderResult(toolInfo.structuredContent) ? toolInfo.structuredContent : undefined;',
    "  const placeOrder = useCallTool('place_order'); // calls the widget-only helper tool",
    '  const { supports } = useLayout();',
    '  const openExternal = useOpenExternal();',
    '  const sendFollowUpMessage = useSendFollowUpMessage();',
    '  const updateModelContext = useUpdateModelContext();',
    "  const publishLifecycle = useWidgetLifecycle('pickup-order');",
    "  const [item, setItem] = useViewState('item', shown?.item ?? 'falafel_wrap'); // survives re-render",
    '  const confirmed = placeOrder.data?.structuredContent as { readonly status?: string } | undefined;',
    '  const total = shown?.total ?? 0;',
    "  const checkoutUrl = shown?.checkoutUrl ?? '';",
    '',
    '  useEffect(() => {',
    '    if (!shown || !supports?.modelContext) return;',
    '    void updateModelContext({',
    "      content: [{ type: 'text', text: `Pickup order: ${item}, total ${total}` }],",
    "      structuredContent: { widget: { name: 'pickup-order', lifecycle: 'active' }, order: { item, total } },",
    '    });',
    '  }, [item, shown, supports?.modelContext, total, updateModelContext]);',
    '',
    '  async function submitOrder() {',
    '    if (!shown) return;',
    '    await placeOrder.callTool({ customer: shown.customer, item });',
    '    if (supports?.modelContext) {',
    "      await publishLifecycle('submitted', { surface: 'order', item, total, status: 'submitted' });",
    '    }',
    '    if (supports?.followUpMessage) {',
    '      await sendFollowUpMessage({ prompt: `The pickup order was submitted for ${item}. Confirm the result.` });',
    '    }',
    '  }',
    '',
    '  if (isPending) return <Feedback status="loading">Loading the order…</Feedback>;',
    '  if (toolInfo.isError) return <Feedback status="error">Could not load the order.</Feedback>;',
    '  if (!shown) return <Feedback status="error">The order result was incomplete.</Feedback>;',
    '',
    '  return (',
    '    // data-llm is an inspection hint; useUpdateModelContext above is the model-visible channel.',
    '    <Frame title="Pickup order" displayMode="auto" data-llm={`Pickup order for ${shown.customer}: ${item}, total ${total}`}>',
    '      <Flow variant="stack">',
    '      <AsyncBoundary state={placeOrder} loading="Placing order…" error={(error) => error.message}>',
    '      <Region title="Order" description="Choose one item for pickup.">',
    '      <Field label="Item">',
    '        <Select value={item} onChange={(event) => setItem(event.currentTarget.value)} options={[',
    "          { value: 'falafel_wrap', label: 'Falafel Wrap' },",
    "          { value: 'lentil_soup', label: 'Lentil Soup' },",
    "          { value: 'mint_lemonade', label: 'Mint Lemonade' },",
    '        ]} />',
    '      </Field>',
    '      </Region>',
    '      {confirmed?.status ? <Feedback status="success">{confirmed.status}</Feedback> : null}',
    '      <ActionBar>',
    '      <Action type="button" variant="primary" disabled={!ready} pending={placeOrder.isPending} pendingLabel="Placing…"',
    '        onClick={submitOrder}',
    '      >',
    '        Place order',
    '      </Action>',
    '      <Action onClick={() => openExternal(checkoutUrl)}>',
    '        Continue checkout',
    '      </Action>',
    '      </ActionBar>',
    '      </AsyncBoundary>',
    '      </Flow>',
    '    </Frame>',
    '  );',
    '}',
    '```',
    '',
    '### 2. The tool declaration',
    '',
    '`tool` declares both the model-visible tool that renders the view and app-only helpers the view calls. Put `visibility: ["app"]` on each helper. Wire `view: { component, entry }`, `csp`, a widget `domain`, and a real `output` schema so non-Apps hosts still receive structured data. Inside `fulfil`, `input` is a symbolic ref recorded into a flow — reference it in output/template strings, but never use it as an object key or `if` condition.',
    '',
    '```ts',
    "import { annotations, server, tool, z } from '@noodleseed/one';",
    '',
    "const item = z.enum(['falafel_wrap', 'lentil_soup', 'mint_lemonade']).default('falafel_wrap');",
    'const checkoutUrl = (customer: string) =>',
    '  `https://orders.example.com/pickup?customer=${customer}`;',
    '',
    'export default server(',
    "  'pickup',",
    '  {',
    "    title: 'Pickup',",
    "    version: '1.0.0',",
    '    // External-link targets the widget opens; the compiler derives ChatGPT redirect_domains from this.',
    "    handoff: { allowedDomains: ['https://orders.example.com'] },",
    '  },',
    '  [',
    "    tool('show_order', {",
    "      description: 'Show the pickup order and render the ordering widget.',",
    '      // Declare tool annotations — a ChatGPT-submission requirement. A read → `readOnly()`.',
    '      annotations: annotations.readOnly(),',
    "      input: z.object({ customer: z.string().default('Guest') }),",
    '      output: z.object({',
    '        customer: z.string(),',
    '        item: z.string(),',
    '        total: z.number(),',
    '        checkoutUrl: z.string(),',
    '      }),',
    '      fulfil: ({ input }) => ({',
    '        customer: input.customer,',
    "        item: 'falafel_wrap',",
    '        total: 12,',
    '        checkoutUrl: checkoutUrl(input.customer),',
    '      }),',
    "      viewTitle: 'Pickup order',",
    "      viewDescription: 'Pick an item and place a pickup order.',",
    '      // A ChatGPT App is this widget + a domain: one https origin per app.',
    "      domain: 'https://pickup.example.com',",
    "      view: { component: 'order-status', entry: './views/order-status.tsx' },",
    '      csp: {',
    "        connectDomains: ['https://orders.example.com'],",
    "        resourceDomains: ['https://example.com'],",
    '        // Keep CSP origins exact and minimal. Add `frameDomains` ONLY if the widget embeds an',
    '        // iframe — it relaxes subframe rendering and triggers stricter ChatGPT review.',
    '      },',
    '    }),',
    "    // Widget-only helper the view calls with useCallTool('place_order'); hidden from the model.",
    "    tool('place_order', {",
    "      visibility: ['app'],",
    "      description: 'Place a pickup order from the widget.',",
    '      // Widget-mediated direct action: explicit false is equivalent to omitting confirmation.',
    '      annotations: annotations.action({ confirm: false }),',
    "      input: z.object({ customer: z.string().default('Guest'), item }),",
    '      output: z.object({ status: z.string(), item: z.string(), checkoutUrl: z.string() }),',
    '      fulfil: ({ input }) => ({',
    '        status: `Order placed for ${input.customer}.`,',
    '        item: input.item,',
    '        checkoutUrl: checkoutUrl(input.customer),',
    '      }),',
    '    }),',
    '  ],',
    ');',
    '```',
    '',
    '## ChatGPT App = this widget + a domain',
    '',
    'A "ChatGPT App" is not a separate authoring surface — it is exactly this MCP Apps widget rendered by the ChatGPT host. From the same declaration you author three things:',
    '',
    '- `domain` on the widget — one https origin per app (required for app-store submission, optional for dev-mode testing).',
    '- `csp: { connectDomains, resourceDomains }` — the exact network/resource origins the widget may reach; keep them minimal. Add `frameDomains` only if the widget embeds an iframe (it relaxes subframe rendering and draws stricter review). These three lists are the complete CSP surface — there is no `base-uri` list.',
    '- server `handoff.allowedDomains` — the external-link targets `useOpenExternal()` opens.',
    '',
    'The compiler emits the rest automatically: the `openai/*` metadata (`openai/outputTemplate`, `openai/widgetCSP`, `openai/widgetDescription`) and ChatGPT’s `redirect_domains` (derived from `handoff.allowedDomains`). `window.openai` and Claude’s ext-apps bridge are auto-detected at startup, so the same widget renders in both Claude and ChatGPT with no host-specific code.',
    '',
    'Verify it in the loop: `noodle check --target chatgpt --json` returning `ok:true` means the widget is **metadata-ready** for ChatGPT’s checks (`domain`, `openai/outputTemplate`, CSP present) — it does NOT prove host rendering, conversation UX, or submission acceptance. Fix any `severity:"error"` finding by its `fix`, then re-check. Validate real rendering in ChatGPT Developer Mode / MCP Inspector as a higher level before submitting.',
    '',
    '**Every tool needs annotations** (`annotations.readOnly()` / `.action()` / `.openAction()`) — missing or wrong `readOnlyHint`/`openWorldHint`/`destructiveHint` is a common submission rejection. **App-store submission is more than building**: a public https endpoint, exact CSP, org verification, app info, screenshots, and test prompts are required — follow OpenAI’s Apps submission guidelines; `noodle check --target chatgpt` covers only the metadata prerequisites.',
    '',
    '## Knowledge/source apps (ChatGPT): search + fetch',
    '',
    'If the app is a read-only knowledge/source connector (docs, wiki, CRM lookups) meant for ChatGPT company-knowledge, implement exactly two tools — `search` and `fetch`, both read-only. ChatGPT only surfaces knowledge apps that match these signatures:',
    '',
    '```ts',
    "import { annotations, server, tool, z } from '@noodleseed/one';",
    '',
    "export default server('kb', { title: 'Knowledge base', version: '1.0.0' }, [",
    "  tool('search', {",
    "    description: 'Search the knowledge base; return citable results.',",
    '    annotations: annotations.readOnly(),',
    '    input: z.object({ query: z.string() }),',
    '    output: z.object({',
    '      results: z.array(z.object({ id: z.string(), title: z.string(), url: z.string() })),',
    '    }),',
    "    fulfil: ({ input }) => ({ results: [{ id: 'doc-1', title: `Match: ${input.query}`, url: 'https://example.com/doc-1' }] }),",
    '  }),',
    "  tool('fetch', {",
    "    description: 'Fetch one document by id for citation.',",
    '    annotations: annotations.readOnly(),',
    '    input: z.object({ id: z.string() }),',
    '    output: z.object({ id: z.string(), title: z.string(), text: z.string(), url: z.string() }),',
    "    fulfil: ({ input }) => ({ id: input.id, title: 'Doc', text: 'Full document text…', url: 'https://example.com/doc-1' }),",
    '  }),',
    ']);',
    '```',
    '',
    '`search` → `{ results: [{ id, title, url }] }`; `fetch` → `{ id, title, text, url, metadata? }`. `url` must be an absolute, user-openable https link for citation.',
    '',
    '## Permissions and host bridge',
    '',
    'Declare extra host capabilities with `permissions` (e.g. `permissions: { clipboardWrite: {} }`). Secrets are never injected into widgets and tool output is redacted before widget delivery. Tool results still carry useful `content`/`structuredContent`, so non-Apps hosts degrade gracefully.',
    '',
    '## Readiness and boundaries',
    '',
    'React views use the app-local Vite bundler. When adding a view to an existing project that does not declare Vite, run `npm install --save-dev vite` before validation.',
    '',
    'Run `noodle validate` first, `noodle check` for widget/Apps readiness, and `noodle devtools` to preview metadata and rendering. Brand via the `server` `branding` tokens (the compiler derives the palette); do not inject raw global CSS.',
  ].join('\n');
}

// ----------------------------------------------------------------------------
// references/examples.md (CURATED index + one canonical server.ts)
// ----------------------------------------------------------------------------

const FLAGSHIP_EXAMPLES: ReadonlyArray<readonly [string, string]> = [
  ['hello', 'Minimal TypeScript quickstart — a single tool, no connectors/widgets.'],
  [
    'weather',
    'HTTP connectors, multi-step flows, a list-returning connector op (whole-array bind + compute narrowing), and the sandboxed compute connector.',
  ],
  [
    'food-ordering',
    'Consumer ordering MCP App widgets, app-only helpers, cart state, assets, branding, and handoff.',
  ],
  [
    'acme-discovery',
    'Top-of-funnel discovery→handoff: a discovery carousel, a `create_handoff` deep link, and a design-first UX spec + wireframe.',
  ],
  [
    'acme-tasks',
    'A two-way productivity app designed around its top-3 prioritized flows (capture/prioritize/complete), with a design-first flow spec + wireframe.',
  ],
  [
    'acme-bistro',
    'End-to-end ordering with a payment-only handoff; ships a gold-standard `design/` set (UX doc, wireframe with compliance audit, API contract).',
  ],
  [
    'customer-auth',
    'End-user OIDC, private customer API routing, route-bound confirmed actions, roles/scopes, and delegated credentials.',
  ],
  [
    'stateful-draft',
    'Review and save a brief before signup; carry caller-scoped state into an account.',
  ],
  ['perplexity', 'A real SaaS API with bearer auth and a managed `secret`.'],
  ['bitcoin', 'API-key HTTP connector, custom auth header, and compute normalization.'],
  [
    'gmail-multi-account',
    'One curated Gmail connector reused by two account bindings, canonical account arrays, exact mutation confirmation, and an accompanying personal-automation skill.',
  ],
  [
    'google-bigquery',
    'Keyless Google Workload Identity Federation with optional service-account impersonation, a BigQuery REST connector, and complete developer/operator setup.',
  ],
  ['sharepoint', 'Microsoft SharePoint delegated Microsoft Entra auth and Graph tools.'],
  [
    'internal-ops-demo',
    'Governed internal connectivity — tools/resources/prompts, role-shaped output.',
  ],
];

export function renderExamplesReference(): string {
  const bundled = new Set(BUNDLED_EXAMPLE_NAMES);
  // Fail fast on drift: a generator-owned bundled name with no FLAGSHIP_EXAMPLES entry would ship
  // its files (via BUNDLED_EXAMPLE_FILES) but silently vanish from this index. Keep them in lockstep.
  const undocumented = BUNDLED_EXAMPLE_NAMES.filter(
    (name) => !FLAGSHIP_EXAMPLES.some(([entryName]) => entryName === name),
  );
  if (undocumented.length > 0) {
    throw new Error(
      `renderExamplesReference: bundled example(s) missing from FLAGSHIP_EXAMPLES: ${undocumented.join(', ')}`,
    );
  }
  const hasDesign = (name: string): boolean =>
    BUNDLED_EXAMPLE_FILES.some((file) => file.relPath.startsWith(`examples/${name}/design/`));

  const bundledRows = FLAGSHIP_EXAMPLES.filter(([name]) => bundled.has(name)).map(
    ([name, useWhen]) => [
      `\`${name}\``,
      useWhen,
      `\`examples/${name}/src/server.ts\`${hasDesign(name) ? ' + `design/`' : ''}`,
    ],
  );
  const repoRows = FLAGSHIP_EXAMPLES.filter(([name]) => !bundled.has(name)).map(
    ([name, useWhen]) => [`\`${name}\``, useWhen],
  );

  return [
    '# Examples',
    '',
    'Flagship examples, one per capability. The **bundled** rows ship inside this skill under `examples/<name>/` (the real `server.ts`, `src/views/*.tsx`, and — for the design-first flagships — a `design/` set); read them locally at the paths shown. The rest live only in the Noodle Seed repository under `examples/<name>/` on GitHub. Extend an existing flagship rather than inventing a new shape.',
    '',
    '## Bundled in this skill — read locally',
    '',
    'Paths are relative to this skill directory. Assets (images/fonts) are omitted from the bundle; fetch the full runnable example from the repository if you need them. Verify any edit with `noodle validate --json` then `noodle test --json`.',
    '',
    mdTable(['Example', 'Use when', 'Read'], bundledRows),
    '',
    '## In the repository only — `examples/<name>/` on GitHub',
    '',
    mdTable(['Example', 'Use when'], repoRows),
    '',
    '## Canonical server.ts',
    '',
    'Author with `server(name, options, definitions)` and top-level helpers:',
    '',
    '```ts',
    "import { server, tool, z } from '@noodleseed/one';",
    '',
    "export default server('hello', { title: 'Hello', version: '1.0.0' }, [",
    "  tool('greet', {",
    "    description: 'Greet someone by name.',",
    '    input: z.object({ name: z.string() }),',
    '    output: z.object({ greeting: z.string() }),',
    '    fulfil: ({ input }) => ({ greeting: `Hello, ${input.name}!` }),',
    '  }),',
    ']);',
    '```',
  ].join('\n');
}
