/** Framework-neutral browser-client and linked-App renderer guidance. */
export function renderEmbeddedAssistantRendererReference(): readonly string[] {
  return [
    '### Framework-neutral DOM client',
    '',
    'Use the same DOM-free client directly without a component wrapper, and import the isolated App-view entry only when rendering linked Apps. The client keeps the session token in memory, and the element owns only App presentation:',
    '',
    '```html',
    '<div id="assistant-app-views"></div>',
    '```',
    '',
    '```ts',
    'import { createAssistantClient } from "@noodleseed/assistant/client";',
    'import "@noodleseed/assistant/app-view";',
    'import {',
    '  type AssistantViewAvailableDetail,',
    '  type NoodleAppViewElement,',
    '} from "@noodleseed/assistant/app-view";',
    '',
    'const assistant = createAssistantClient({',
    '  sessionEndpoint: "/api/assistant/session",',
    '  clientContext: () => ({',
    '    locale: navigator.language,',
    '    timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,',
    '  }),',
    '});',
    '',
    'const appViews = document.querySelector("#assistant-app-views");',
    'if (!appViews) throw new Error("Missing App views host");',
    'const mountedViews = new Map<string, NoodleAppViewElement>();',
    'const readResolvedTheme = (): "light" | "dark" =>',
    '  document.documentElement.classList.contains("dark") ? "dark" : "light";',
    'let resolvedTheme: "light" | "dark" = readResolvedTheme();',
    'const syncResolvedTheme = () => {',
    '  resolvedTheme = readResolvedTheme();',
    '  for (const mountedView of mountedViews.values()) mountedView.theme = resolvedTheme;',
    '};',
    'new MutationObserver(syncResolvedTheme).observe(document.documentElement, {',
    '  attributes: true,',
    '  attributeFilter: ["class"],',
    '});',
    'const appViewFor = (view: AssistantViewAvailableDetail) => {',
    '  const key = `${view.id}:${view.resourceUri}`;',
    '  let appView = mountedViews.get(key);',
    '  if (!appView) {',
    '    appView = document.createElement("noodle-app-view") as NoodleAppViewElement;',
    '    appView.client = assistant;',
    '    mountedViews.set(key, appView);',
    '    appViews.append(appView);',
    '  }',
    '  appView.theme = resolvedTheme;',
    '  return appView;',
    '};',
    '',
    'assistant.updateModelContext({',
    "  content: [{ type: 'text', text: 'The time-off form is mounted.' }],",
    "  structuredContent: { widget: { name: 'time-off', lifecycle: 'mounted' } },",
    '});',
    '',
    'assistant.subscribeChat((state) => {',
    '  renderUIMessageState(state, {',
    '    respond: (id, response) => assistant.respond(id, response),',
    '  });',
    '  const activeViewKeys = new Set<string>();',
    '  for (const message of state.messages) {',
    '    for (const part of message.parts) {',
    "      if (part.type === 'data-view') {",
    '        const key = `${part.data.id}:${part.data.resourceUri}`;',
    '        activeViewKeys.add(key);',
    '        appViewFor(part.data).view = part.data;',
    '      }',
    '    }',
    '  }',
    '  for (const [key, mountedView] of mountedViews) {',
    '    if (!activeViewKeys.has(key)) {',
    '      mountedView.remove();',
    '      mountedViews.delete(key);',
    '    }',
    '  }',
    '});',
    '```',
    '',
    '`subscribeChat` immediately emits a detached `{ messages, status, error? }` snapshot and then emits as `UIMessage.parts` change. Text uses `text`; Noodle confirmations, input requests, sign-in requests, tool results, and linked views use `data-confirmation`, `data-input-request`, `data-sign-in`, `data-tool-result`, and `data-view`. `renderUIMessageState` is application code: it must show a complete schema-aware review or requested form and require an explicit user gesture before calling the supplied `respond`. Never call `respond` while scanning a transcript snapshot. Interaction data moves through pending/submitting/accepted/declined/cancelled. Use raw `subscribe(...)` only for transport/session lifecycle events that are not transcript content.',
    '',
    'For a chat-first custom host, raw `tool_started` carries the direct invocation call `id` and technical `tool` name before execution. Map known tools through a finite application-owned label table and use a neutral fallback such as "Working"; never mechanically expose an internal identifier as customer copy. Reserve one stable region with `role="status"` and `aria-live="polite"` for thinking, the mapped activity label, and the linked-view skeleton. `view_available` makes the view ready; raw `error` or chat `error` replaces it with `role="alert"`. Mark decorative skeleton shapes `aria-hidden="true"` and disable shimmer/transitions under `@media (prefers-reduced-motion: reduce)`.',
    '',
    '```ts',
    'const activityByTool: Readonly<Record<string, string>> = {',
    '  list_open_items: "Loading open items",',
    '};',
    'const viewSlots = new Map([["ui://workspace/current", "current-workspace"]]);',
    '',
    'assistant.subscribe((event) => {',
    '  if (event.event === "tool_started") {',
    '    showActivity(event.data.id, activityByTool[event.data.tool] ?? "Working");',
    '  }',
    '  if (event.event === "view_available") {',
    '    const key = viewSlots.get(event.data.resourceUri) ?? `${event.data.id}:${event.data.resourceUri}`;',
    '    showReadyView(key, event.data);',
    '  }',
    '  if (event.event === "error") showActivityError(event.data.code);',
    '});',
    '```',
    '',
    '`data-view` means a completed tool has a linked MCP App view. Pass that typed part and the existing client to `<noodle-app-view>` in another component framework or plain DOM, or to its `NoodleAppView` React adapter. It retains one bridge for client + `view.id` + `view.resourceUri` and requests standard App teardown on semantic replacement, disconnect, or App request. That pair is transport identity: different call ids are distinct invocations and must not be deduplicated generically. If the product intentionally owns one current panel for a known resource, declare an application-owned slot map and replace only that slot. Deliberately map the bounded result to an application-trusted native component only when replacing the linked App UI.',
    '',
  ];
}
