import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { runAssistantEmbed } from '../src/commands/assistant-embed-ops.js';

const roots: string[] = [];
function workspace(): string {
  const root = mkdtempSync(join(tmpdir(), 'noodle-integration-plan-'));
  roots.push(root);
  return root;
}

interface PlanReport {
  readonly data?: {
    readonly dryRun: boolean;
    readonly surface: string;
    readonly files: readonly { path: string; action: string; sha256: string; content?: string }[];
    readonly recipe: {
      id: string;
      version: number;
      fingerprint: string;
      applicationSeams: readonly string[];
    };
    readonly nextSteps: readonly string[];
    readonly integrationVerified: false;
  };
  readonly error?: { code: string };
}

async function run(dir: string, flags: readonly string[] = [], agents = false) {
  const logs: string[] = [];
  vi.spyOn(console, 'log').mockImplementation((value) => logs.push(String(value)));
  const code = await runAssistantEmbed(
    ['--dir', dir, '--json', ...(agents ? [] : ['--no-agents']), ...flags],
    {},
    {},
  );
  return { code, report: JSON.parse(logs.join('\n')) as PlanReport, output: logs.join('\n') };
}

afterEach(() => {
  vi.restoreAllMocks();
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('inspectable assistant integration installation', () => {
  it('previews exact generated bytes and provenance without creating the target or agent files', async () => {
    const target = join(workspace(), 'app');
    const result = await run(target, ['--surface', 'public', '--dry-run']);
    expect(result.code).toBe(0);
    expect(existsSync(target)).toBe(false);
    expect(result.report.data).toMatchObject({
      dryRun: true,
      surface: 'public',
      integrationVerified: false,
    });
    expect(result.report.data?.recipe).toMatchObject({ id: 'nextjs-public', version: 1 });
    expect(result.report.data?.recipe.fingerprint).toMatch(/^[a-f0-9]{64}$/);
    for (const file of result.report.data?.files ?? []) {
      expect(file.sha256).toMatch(/^[a-f0-9]{64}$/);
      expect(file.content).toBeTypeOf('string');
    }
    expect(result.output).not.toContain('NOODLE_ASSISTANT_CLIENT_SECRET');
  });

  it('applies the selected profile and reruns without rewriting identical files', async () => {
    const target = workspace();
    const preview = await run(target, ['--surface', 'public', '--dry-run']);
    const applied = await run(target, ['--surface', 'public']);
    expect(applied.code).toBe(0);
    expect(applied.report.data?.recipe.fingerprint).toBe(preview.report.data?.recipe.fingerprint);
    expect(existsSync(join(target, 'app/api/assistant/session/route.ts'))).toBe(false);
    for (const file of preview.report.data?.files ?? [])
      expect(readFileSync(join(target, file.path), 'utf8')).toBe(file.content);
    const again = await run(target, ['--surface', 'public']);
    expect(again.report.data?.files.every((file) => file.action === 'unchanged')).toBe(true);
  });

  it('previews default agent setup without creating the target directory', async () => {
    const target = join(workspace(), 'app');
    const result = await run(target, ['--surface', 'public', '--dry-run'], true);
    expect(result.code).toBe(0);
    expect(existsSync(target)).toBe(false);
  });

  it('checks agent instruction paths before writing integration files', async () => {
    const target = workspace();
    const outside = join(workspace(), 'instructions.md');
    writeFileSync(outside, '# Private instructions\n');
    symlinkSync(outside, join(target, 'AGENTS.md'));
    const result = await run(target, ['--surface', 'public', '--force'], true);
    expect(result.code).not.toBe(0);
    expect(result.report.error?.code).toBe('assistant_embed_unsafe_path');
    expect(readFileSync(outside, 'utf8')).toBe('# Private instructions\n');
    expect(existsSync(join(target, 'components/noodle-assistant.tsx'))).toBe(false);
  });

  it('preserves edited files and never prints their contents during inspection', async () => {
    const target = workspace();
    await run(target, ['--surface', 'public']);
    const path = join(target, 'components/noodle-assistant.tsx');
    const privateSource = '// private customer code, never include in CLI output\n';
    writeFileSync(path, privateSource);
    const preview = await run(target, ['--surface', 'public', '--dry-run']);
    expect(preview.report.data?.files).toContainEqual(
      expect.objectContaining({ path: 'components/noodle-assistant.tsx', action: 'skipped' }),
    );
    expect(preview.output).not.toContain(privateSource.trim());
    expect(readFileSync(path, 'utf8')).toBe(privateSource);
  });

  it('rejects invalid surfaces before writing anything', async () => {
    const target = join(workspace(), 'app');
    const result = await run(target, ['--surface', 'unknown']);
    expect(result.code).not.toBe(0);
    expect(result.report.error?.code).toBe('assistant_host_surface_invalid');
    expect(existsSync(target)).toBe(false);
  });

  it('rejects a symlinked output directory even with force', async () => {
    const target = workspace();
    const outside = workspace();
    mkdirSync(join(target, 'app'));
    symlinkSync(outside, join(target, 'components'));
    const result = await run(target, ['--surface', 'public', '--force']);
    expect(result.code).not.toBe(0);
    expect(result.report.error?.code).toBe('assistant_embed_unsafe_path');
    expect(existsSync(join(outside, 'noodle-assistant.tsx'))).toBe(false);
    expect(existsSync(join(target, '.env.local.example'))).toBe(false);
  });

  it('returns actionable next steps with the exact generated identity symbol in JSON', async () => {
    const result = await run(workspace(), ['--dry-run']);
    expect(result.report.data?.nextSteps.join('\n')).toContain('authenticateAssistantRequest');
    expect(result.output).not.toContain('requireCurrentUser');
    expect(result.report.data?.integrationVerified).toBe(false);
  });
});
